//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrencyConversion_Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="CurrencyConversion.Service", ConfigurationName="ServiceReference1.ICurrencyConversionService")]
    public interface ICurrencyConversionService {
        
        [System.ServiceModel.OperationContractAttribute(Action="CurrencyConversion.Service/ICurrencyConversionService/Convert", ReplyAction="CurrencyConversion.Service/ICurrencyConversionService/ConvertResponse")]
        string Convert(double input);
        
        [System.ServiceModel.OperationContractAttribute(Action="CurrencyConversion.Service/ICurrencyConversionService/Convert", ReplyAction="CurrencyConversion.Service/ICurrencyConversionService/ConvertResponse")]
        System.Threading.Tasks.Task<string> ConvertAsync(double input);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ICurrencyConversionServiceChannel : CurrencyConversion_Client.ServiceReference1.ICurrencyConversionService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CurrencyConversionServiceClient : System.ServiceModel.ClientBase<CurrencyConversion_Client.ServiceReference1.ICurrencyConversionService>, CurrencyConversion_Client.ServiceReference1.ICurrencyConversionService {
        
        public CurrencyConversionServiceClient() {
        }
        
        public CurrencyConversionServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CurrencyConversionServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConversionServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CurrencyConversionServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string Convert(double input) {
            return base.Channel.Convert(input);
        }
        
        public System.Threading.Tasks.Task<string> ConvertAsync(double input) {
            return base.Channel.ConvertAsync(input);
        }
    }
}
